"""vendor_responses, vendor_names, vendor_reclassified flags

Revision ID: ff5f5ec489ba
Revises: 3a9e5c1d7f20
Create Date: 2026-10-01 16:25:02.415970

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "ff5f5ec489ba"
down_revision: str | None = "3a9e5c1d7f20"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vendor_names",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("vendor_name", sa.String(length=200), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_vendor_names_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_names")),
        sa.UniqueConstraint(
            "provider", "instrument_id", name=op.f("uq_vendor_names_provider_instrument_id")
        ),
    )
    op.create_table(
        "vendor_responses",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=True),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("endpoint", sa.String(length=64), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("params_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("raw_path", sa.String(length=512), nullable=True),
        sa.Column("identity_ok", sa.Boolean(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_vendor_responses_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_responses")),
    )
    op.create_index(
        "ix_vendor_responses_lookup",
        "vendor_responses",
        ["provider", "instrument_id", "endpoint", "params_hash"],
        unique=False,
    )
    op.add_column(
        "fin_annual",
        sa.Column("vendor_reclassified", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "fin_line_items",
        sa.Column("vendor_reclassified", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "fin_quarterly",
        sa.Column("vendor_reclassified", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fin_quarterly", "vendor_reclassified")
    op.drop_column("fin_line_items", "vendor_reclassified")
    op.drop_column("fin_annual", "vendor_reclassified")
    op.drop_index("ix_vendor_responses_lookup", table_name="vendor_responses")
    op.drop_table("vendor_responses")
    op.drop_table("vendor_names")
    # ### end Alembic commands ###
