"""annual_reports ledger, pdf_line_candidates (review queue), fin_line_items PDF columns
(SPEC v0.2 §3.6 step 3: annual-report PDF gap filler)

Revision ID: a4e5f6b7c8d9
Revises: f3d4e5a6b7c8
Create Date: 2026-09-30 02:51:42.583725

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a4e5f6b7c8d9"
down_revision: str | None = "f3d4e5a6b7c8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "annual_reports",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("exchange", sa.String(length=16), nullable=False),
        sa.Column("document", sa.String(length=512), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=True),
        sa.Column("disseminated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usable_from", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "parsed",
                "failed",
                name="filingstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("raw_path", sa.String(length=512), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("statements", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("labels_version", sa.Integer(), nullable=True),
        sa.Column("parsed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_annual_reports_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_annual_reports")),
        sa.UniqueConstraint(
            "instrument_id", "document", name=op.f("uq_annual_reports_instrument_id_document")
        ),
    )
    op.create_index("ix_annual_reports_status", "annual_reports", ["status"], unique=False)
    op.create_table(
        "pdf_line_candidates",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("annual_report_id", sa.BigInteger(), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column(
            "statement",
            sa.Enum(
                "pl",
                "bs",
                "cf",
                "ratio",
                name="linestatement",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "basis",
            sa.Enum(
                "consolidated",
                "standalone",
                name="statementtype",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column(
            "period_type",
            sa.Enum(
                "quarter",
                "year",
                "instant",
                name="periodtype",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("item_code", sa.String(length=64), nullable=False),
        sa.Column("value_inr", sa.Double(), nullable=True),
        sa.Column("raw_value", sa.Double(), nullable=False),
        sa.Column("raw_label", sa.String(length=512), nullable=False),
        sa.Column("pages", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Double(), nullable=False),
        sa.Column("reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "auto_accepted",
                "pending",
                "accepted",
                "corrected",
                "rejected",
                name="reviewstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("corrected_value_inr", sa.Double(), nullable=True),
        sa.Column("stored", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["annual_report_id"],
            ["annual_reports.id"],
            name=op.f("fk_pdf_line_candidates_annual_report_id_annual_reports"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_pdf_line_candidates_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pdf_line_candidates")),
        sa.UniqueConstraint(
            "annual_report_id",
            "basis",
            "statement",
            "period_end",
            "item_code",
            name="uq_pdf_line_candidates_key",
        ),
    )
    op.create_index(
        "ix_pdf_line_candidates_instrument",
        "pdf_line_candidates",
        ["instrument_id", "period_end"],
        unique=False,
    )
    op.create_index(
        "ix_pdf_line_candidates_status", "pdf_line_candidates", ["status"], unique=False
    )
    op.add_column("fin_line_items", sa.Column("annual_report_id", sa.BigInteger(), nullable=True))
    op.add_column("fin_line_items", sa.Column("confidence", sa.Double(), nullable=True))
    op.create_foreign_key(
        op.f("fk_fin_line_items_annual_report_id_annual_reports"),
        "fin_line_items",
        "annual_reports",
        ["annual_report_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        "ix_fin_line_items_annual_report", "fin_line_items", ["annual_report_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_fin_line_items_annual_report", table_name="fin_line_items")
    op.drop_constraint(
        op.f("fk_fin_line_items_annual_report_id_annual_reports"),
        "fin_line_items",
        type_="foreignkey",
    )
    op.drop_column("fin_line_items", "confidence")
    op.drop_column("fin_line_items", "annual_report_id")
    op.drop_index("ix_pdf_line_candidates_status", table_name="pdf_line_candidates")
    op.drop_index("ix_pdf_line_candidates_instrument", table_name="pdf_line_candidates")
    op.drop_table("pdf_line_candidates")
    op.drop_index("ix_annual_reports_status", table_name="annual_reports")
    op.drop_table("annual_reports")
    # ### end Alembic commands ###
