"""price anomalies

Revision ID: 848456d5b0a6
Revises: ff5f5ec489ba
Create Date: 2026-10-01 17:19:36.335758

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "848456d5b0a6"
down_revision: str | None = "ff5f5ec489ba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "price_anomalies",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("ratio", sa.Double(), nullable=False),
        sa.Column("candidate", sa.Double(), nullable=False),
        sa.Column("volume_ratio", sa.Double(), nullable=True),
        sa.Column("volume_confirmed", sa.Boolean(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("action_ex_date", sa.Date(), nullable=True),
        sa.Column("ratio_old", sa.Integer(), nullable=True),
        sa.Column("ratio_new", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_price_anomalies_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_anomalies")),
        sa.UniqueConstraint(
            "instrument_id", "day", name=op.f("uq_price_anomalies_instrument_id_day")
        ),
    )
    op.add_column(
        "corporate_actions", sa.Column("price_adjusted_by_source", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("corporate_actions", "price_adjusted_by_source")
    op.drop_table("price_anomalies")
    # ### end Alembic commands ###
