"""initial schema

Revision ID: b50ffa78a35a
Revises:
Create Date: 2026-09-29 00:21:19.384844

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b50ffa78a35a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "broker_tokens",
        sa.Column(
            "broker",
            sa.Enum(
                "fyers", "kite", name="broker", native_enum=False, create_constraint=True, length=32
            ),
            nullable=False,
        ),
        sa.Column("access_token_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("broker", name=op.f("pk_broker_tokens")),
    )
    op.create_table(
        "instruments",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("isin", sa.String(length=12), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("series", sa.String(length=8), nullable=True),
        sa.Column("industry", sa.String(length=200), nullable=True),
        sa.Column("sector", sa.String(length=64), nullable=True),
        sa.Column("is_index", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("listing_date", sa.Date(), nullable=True),
        sa.Column("face_value", sa.Double(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instruments")),
        sa.UniqueConstraint("isin", name=op.f("uq_instruments_isin")),
        sa.UniqueConstraint("symbol", name=op.f("uq_instruments_symbol")),
    )
    op.create_table(
        "job_runs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("job_name", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "success",
                "failed",
                name="jobstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("rows_written", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_runs")),
    )
    op.create_index("ix_job_runs_job_started", "job_runs", ["job_name", "started_at"], unique=False)
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column(
            "alert_type",
            sa.Enum(
                "enters_buy_zone",
                "crosses_fv",
                "crosses_top_band",
                "crosses_invalidation",
                name="alerttype",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("last_triggered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_triggered_price", sa.Double(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_alerts_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
        sa.UniqueConstraint(
            "instrument_id", "alert_type", name=op.f("uq_alerts_instrument_id_alert_type")
        ),
    )
    op.create_table(
        "corporate_actions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("ex_date", sa.Date(), nullable=False),
        sa.Column(
            "action_type",
            sa.Enum(
                "split",
                "bonus",
                "dividend",
                "rights",
                "other",
                name="corporateactiontype",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("record_date", sa.Date(), nullable=True),
        sa.Column("announcement_date", sa.Date(), nullable=True),
        sa.Column("ratio_old", sa.Double(), nullable=True),
        sa.Column("ratio_new", sa.Double(), nullable=True),
        sa.Column("dividend_per_share", sa.Double(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_corporate_actions_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_corporate_actions")),
        sa.UniqueConstraint(
            "instrument_id",
            "ex_date",
            "action_type",
            name=op.f("uq_corporate_actions_instrument_id_ex_date_action_type"),
        ),
    )
    op.create_table(
        "data_gaps",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=True),
        sa.Column("dataset", sa.String(length=32), nullable=False),
        sa.Column("field", sa.String(length=64), nullable=True),
        sa.Column("period", sa.Date(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "providers_tried",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_data_gaps_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_gaps")),
        sa.UniqueConstraint(
            "instrument_id",
            "dataset",
            "field",
            "period",
            name=op.f("uq_data_gaps_instrument_id_dataset_field_period"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_table(
        "delivery_daily",
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("traded_qty", sa.BigInteger(), nullable=True),
        sa.Column("deliverable_qty", sa.BigInteger(), nullable=True),
        sa.Column("delivery_pct", sa.Double(), nullable=True),
        sa.Column("traded_value_cr", sa.Double(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_delivery_daily_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("instrument_id", "date", name=op.f("pk_delivery_daily")),
    )
    op.create_table(
        "fin_annual",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=False),
        sa.Column("total_assets", sa.Double(), nullable=True),
        sa.Column("current_liabilities", sa.Double(), nullable=True),
        sa.Column("total_equity", sa.Double(), nullable=True),
        sa.Column("minority_interest_bs", sa.Double(), nullable=True),
        sa.Column("total_debt", sa.Double(), nullable=True),
        sa.Column("cash_and_equivalents", sa.Double(), nullable=True),
        sa.Column("non_operating_investments", sa.Double(), nullable=True),
        sa.Column("receivables", sa.Double(), nullable=True),
        sa.Column("inventory", sa.Double(), nullable=True),
        sa.Column("payables", sa.Double(), nullable=True),
        sa.Column("net_block", sa.Double(), nullable=True),
        sa.Column("book_value_per_share", sa.Double(), nullable=True),
        sa.Column("cfo", sa.Double(), nullable=True),
        sa.Column("purchase_of_fixed_assets", sa.Double(), nullable=True),
        sa.Column("sale_of_fixed_assets", sa.Double(), nullable=True),
        sa.Column("dividends_paid", sa.Double(), nullable=True),
        sa.Column(
            "statement_type",
            sa.Enum(
                "consolidated",
                "standalone",
                name="statementtype",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("announcement_date", sa.Date(), nullable=True),
        sa.Column("revenue", sa.Double(), nullable=True),
        sa.Column("cogs", sa.Double(), nullable=True),
        sa.Column("ebitda", sa.Double(), nullable=True),
        sa.Column("other_income", sa.Double(), nullable=True),
        sa.Column("depreciation", sa.Double(), nullable=True),
        sa.Column("ebit", sa.Double(), nullable=True),
        sa.Column("interest", sa.Double(), nullable=True),
        sa.Column("pbt", sa.Double(), nullable=True),
        sa.Column("tax", sa.Double(), nullable=True),
        sa.Column("pat", sa.Double(), nullable=True),
        sa.Column("minority_interest_pl", sa.Double(), nullable=True),
        sa.Column("eps_diluted", sa.Double(), nullable=True),
        sa.Column("shares_diluted_cr", sa.Double(), nullable=True),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_fin_annual_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fin_annual")),
        sa.UniqueConstraint(
            "instrument_id",
            "statement_type",
            "period_end",
            name=op.f("uq_fin_annual_instrument_id_statement_type_period_end"),
        ),
    )
    op.create_index(
        "ix_fin_annual_instrument_announcement",
        "fin_annual",
        ["instrument_id", "announcement_date"],
        unique=False,
    )
    op.create_table(
        "fin_quarterly",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column(
            "statement_type",
            sa.Enum(
                "consolidated",
                "standalone",
                name="statementtype",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("announcement_date", sa.Date(), nullable=True),
        sa.Column("revenue", sa.Double(), nullable=True),
        sa.Column("cogs", sa.Double(), nullable=True),
        sa.Column("ebitda", sa.Double(), nullable=True),
        sa.Column("other_income", sa.Double(), nullable=True),
        sa.Column("depreciation", sa.Double(), nullable=True),
        sa.Column("ebit", sa.Double(), nullable=True),
        sa.Column("interest", sa.Double(), nullable=True),
        sa.Column("pbt", sa.Double(), nullable=True),
        sa.Column("tax", sa.Double(), nullable=True),
        sa.Column("pat", sa.Double(), nullable=True),
        sa.Column("minority_interest_pl", sa.Double(), nullable=True),
        sa.Column("eps_diluted", sa.Double(), nullable=True),
        sa.Column("shares_diluted_cr", sa.Double(), nullable=True),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_fin_quarterly_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fin_quarterly")),
        sa.UniqueConstraint(
            "instrument_id",
            "statement_type",
            "period_end",
            name=op.f("uq_fin_quarterly_instrument_id_statement_type_period_end"),
        ),
    )
    op.create_index(
        "ix_fin_quarterly_instrument_announcement",
        "fin_quarterly",
        ["instrument_id", "announcement_date"],
        unique=False,
    )
    op.create_table(
        "index_membership",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("index_name", sa.String(length=64), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("weight_pct", sa.Double(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_index_membership_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_index_membership")),
        sa.UniqueConstraint(
            "index_name",
            "instrument_id",
            "effective_from",
            name=op.f("uq_index_membership_index_name_instrument_id_effective_from"),
        ),
    )
    op.create_table(
        "prices_daily",
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("open", sa.Double(), nullable=False),
        sa.Column("high", sa.Double(), nullable=False),
        sa.Column("low", sa.Double(), nullable=False),
        sa.Column("close", sa.Double(), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column("adj_factor", sa.Double(), nullable=True),
        sa.Column("adj_open", sa.Double(), nullable=True),
        sa.Column("adj_high", sa.Double(), nullable=True),
        sa.Column("adj_low", sa.Double(), nullable=True),
        sa.Column("adj_close", sa.Double(), nullable=True),
        sa.Column("adj_volume", sa.BigInteger(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_prices_daily_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("instrument_id", "date", name=op.f("pk_prices_daily")),
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("thesis", sa.Text(), nullable=True),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_reports_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
        sa.UniqueConstraint("instrument_id", "as_of", name=op.f("uq_reports_instrument_id_as_of")),
    )
    op.create_table(
        "scores",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("quality", sa.Double(), nullable=True),
        sa.Column("growth", sa.Double(), nullable=True),
        sa.Column("valuation", sa.Double(), nullable=True),
        sa.Column("health", sa.Double(), nullable=True),
        sa.Column("governance", sa.Double(), nullable=True),
        sa.Column("technical", sa.Double(), nullable=True),
        sa.Column("total", sa.Double(), nullable=True),
        sa.Column("provisional_grade", sa.String(length=4), nullable=True),
        sa.Column("grade", sa.String(length=4), nullable=True),
        sa.Column(
            "knockouts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("earned_premium", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=32), nullable=True),
        sa.Column("sub_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "reasons", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_scores_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scores")),
        sa.UniqueConstraint("instrument_id", "as_of", name=op.f("uq_scores_instrument_id_as_of")),
    )
    op.create_table(
        "shareholding",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("filing_date", sa.Date(), nullable=True),
        sa.Column("promoter_pct", sa.Double(), nullable=True),
        sa.Column("promoter_pledge_pct", sa.Double(), nullable=True),
        sa.Column("fii_pct", sa.Double(), nullable=True),
        sa.Column("dii_pct", sa.Double(), nullable=True),
        sa.Column("mf_pct", sa.Double(), nullable=True),
        sa.Column("public_pct", sa.Double(), nullable=True),
        sa.Column("num_shareholders", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_shareholding_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shareholding")),
        sa.UniqueConstraint(
            "instrument_id", "period_end", name=op.f("uq_shareholding_instrument_id_period_end")
        ),
    )
    op.create_table(
        "surveillance_flags",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column(
            "list_name",
            sa.Enum(
                "asm_lt",
                "asm_st",
                "gsm",
                "fno_ban",
                name="surveillancelist",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("stage", sa.String(length=16), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_surveillance_flags_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_surveillance_flags")),
        sa.UniqueConstraint(
            "instrument_id",
            "list_name",
            "effective_from",
            name=op.f("uq_surveillance_flags_instrument_id_list_name_effective_from"),
        ),
    )
    op.create_table(
        "technical_snapshots",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column(
            "timeframe",
            sa.Enum(
                "daily",
                "weekly",
                name="timeframe",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("stage", sa.Integer(), nullable=True),
        sa.Column("rs_percentile", sa.Double(), nullable=True),
        sa.Column("trend_state", sa.String(length=32), nullable=True),
        sa.Column("buy_zone_low", sa.Double(), nullable=True),
        sa.Column("buy_zone_high", sa.Double(), nullable=True),
        sa.Column("invalidation", sa.Double(), nullable=True),
        sa.Column("atr", sa.Double(), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "reasons", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "stage BETWEEN 1 AND 4", name=op.f("ck_technical_snapshots_stage_range")
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_technical_snapshots_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_technical_snapshots")),
        sa.UniqueConstraint(
            "instrument_id",
            "as_of",
            "timeframe",
            name=op.f("uq_technical_snapshots_instrument_id_as_of_timeframe"),
        ),
    )
    op.create_table(
        "user_overrides",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_user_overrides_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_overrides")),
        sa.UniqueConstraint(
            "instrument_id", "key", name=op.f("uq_user_overrides_instrument_id_key")
        ),
    )
    op.create_table(
        "valuation_snapshots",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("cmp", sa.Double(), nullable=True),
        sa.Column("baseline", sa.Double(), nullable=True),
        sa.Column("fair_value", sa.Double(), nullable=True),
        sa.Column("top_band", sa.Double(), nullable=True),
        sa.Column("mos_pct", sa.Double(), nullable=True),
        sa.Column("zone", sa.String(length=32), nullable=True),
        sa.Column("confidence", sa.String(length=16), nullable=True),
        sa.Column("methods", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reverse_dcf", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("sensitivity", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "reasons", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_valuation_snapshots_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_valuation_snapshots")),
        sa.UniqueConstraint(
            "instrument_id", "as_of", name=op.f("uq_valuation_snapshots_instrument_id_as_of")
        ),
    )
    op.create_table(
        "watchlist",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_watchlist_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlist")),
        sa.UniqueConstraint("instrument_id", name=op.f("uq_watchlist_instrument_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("watchlist")
    op.drop_table("valuation_snapshots")
    op.drop_table("user_overrides")
    op.drop_table("technical_snapshots")
    op.drop_table("surveillance_flags")
    op.drop_table("shareholding")
    op.drop_table("scores")
    op.drop_table("reports")
    op.drop_table("prices_daily")
    op.drop_table("index_membership")
    op.drop_index("ix_fin_quarterly_instrument_announcement", table_name="fin_quarterly")
    op.drop_table("fin_quarterly")
    op.drop_index("ix_fin_annual_instrument_announcement", table_name="fin_annual")
    op.drop_table("fin_annual")
    op.drop_table("delivery_daily")
    op.drop_table("data_gaps")
    op.drop_table("corporate_actions")
    op.drop_table("alerts")
    op.drop_index("ix_job_runs_job_started", table_name="job_runs")
    op.drop_table("job_runs")
    op.drop_table("instruments")
    op.drop_table("broker_tokens")
    # ### end Alembic commands ###
